In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
from sci_helpers import csv_to_samples_list
from sci_helpers import compare_wrangled

In [2]:
# Example call (adjust filepath):
s_list, ox_order, df_num = csv_to_samples_list('Aplites_HAL_XRF_noUncertainty.csv', filepath=r'C:\Users\marvi\PycharmProjects\sci-cluster\sci-cluster\sci-data\Aplites_XRF_data')
print(ox_order)
print(s_list[0])
print(df_num)

['SiO2', 'TiO2', 'Al2O3', 'FeO*', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
['KCP109C', np.float64(75.82), np.float64(0.082), np.float64(12.95), np.float64(0.66), np.float64(0.031), np.float64(0.09), np.float64(0.7), np.float64(4.37), np.float64(4.01), np.float64(0.009)]
             KCP109C  KCP109B  KCP109A  KHD-106-A  KHD-105-G  KHD-105-D  \
Sample Name
SiO2          75.820   76.360   76.620     75.800     76.230     76.070
TiO2           0.082    0.069    0.079      0.131      0.058      0.092
Al2O3         12.950   12.650   12.480     12.900     13.050     13.070
FeO*           0.660    0.520    0.620      1.100      0.450      0.640
MnO            0.031    0.024    0.026      0.035      0.005      0.008
MgO            0.090    0.050    0.060      0.160      0.050      0.080
CaO            0.700    0.540    0.530      1.060      0.960      1.040
Na2O           4.370    3.970    3.980      3.210      3.080      3.430
K2O            4.010    4.610    4.460      4.980      5.430      4.850
P2O5           0.009    0.006    0.004      0.052      0.005      0.010

             KHD-105-E  KKC-103-A  KHD-105-B  KHD-105-F  KHD-107-C  KCP-114-A  \
Sample Name
SiO2            76.360     76.420     76.190     71.780     74.330     76.100
TiO2             0.091      0.079      0.076      0.249      0.173      0.133
Al2O3           12.950     12.860     12.980     14.620     13.450     12.930
FeO*             0.590      0.500      0.590      2.030      1.390      0.830
MnO              0.008      0.006      0.007      0.042      0.020      0.022
MgO              0.070      0.060      0.070      0.370      0.250      0.190
CaO              0.900      1.010      1.000      2.170      1.460      1.140
Na2O             3.230      2.840      2.950      3.790      3.110      3.470
K2O              5.340      5.620      5.540      4.130      5.220      4.630
P2O5             0.008      0.034      0.014      0.083      0.059      0.044

             KHD-107-A  KHD-107-D  KHD-105-B-2
Sample Name
SiO2            75.450     75.430       76.120
TiO2             0.091      0.141        0.095
Al2O3           13.130     13.060       12.820
FeO*             0.800      0.790        0.850
MnO              0.016      0.014        0.010
MgO              0.090      0.220        0.120
CaO              0.960      1.170        0.940
Na2O             2.940      2.740        2.810
K2O              5.910      5.820        5.670
P2O5             0.028      0.035        0.013

Below is a test call of the function 'csv_to_samples_list' , but applied to my aplite dataset.

In [3]:
s_list, ox_order, df_num = csv_to_samples_list('Aplites_HAL_XRF_noUncertainty.csv',filepath=r'C:\Users\marvi\PycharmProjects\sci-cluster\sci-cluster\sci-data\Aplites_XRF_data')
print(ox_order)
print(s_list[0])
print(df_num)

['SiO2', 'TiO2', 'Al2O3', 'FeO*', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
['KCP109C', np.float64(75.82), np.float64(0.082), np.float64(12.95), np.float64(0.66), np.float64(0.031), np.float64(0.09), np.float64(0.7), np.float64(4.37), np.float64(4.01), np.float64(0.009)]
             KCP109C  KCP109B  KCP109A  KHD-106-A  KHD-105-G  KHD-105-D  \
Sample Name
SiO2          75.820   76.360   76.620     75.800     76.230     76.070
TiO2           0.082    0.069    0.079      0.131      0.058      0.092
Al2O3         12.950   12.650   12.480     12.900     13.050     13.070
FeO*           0.660    0.520    0.620      1.100      0.450      0.640
MnO            0.031    0.024    0.026      0.035      0.005      0.008
MgO            0.090    0.050    0.060      0.160      0.050      0.080
CaO            0.700    0.540    0.530      1.060      0.960      1.040
Na2O           4.370    3.970    3.980      3.210      3.080      3.430
K2O            4.010    4.610    4.460      4.980      5.430      4.850
P2O5           0.009    0.006    0.004      0.052      0.005      0.010

             KHD-105-E  KKC-103-A  KHD-105-B  KHD-105-F  KHD-107-C  KCP-114-A  \
Sample Name
SiO2            76.360     76.420     76.190     71.780     74.330     76.100
TiO2             0.091      0.079      0.076      0.249      0.173      0.133
Al2O3           12.950     12.860     12.980     14.620     13.450     12.930
FeO*             0.590      0.500      0.590      2.030      1.390      0.830
MnO              0.008      0.006      0.007      0.042      0.020      0.022
MgO              0.070      0.060      0.070      0.370      0.250      0.190
CaO              0.900      1.010      1.000      2.170      1.460      1.140
Na2O             3.230      2.840      2.950      3.790      3.110      3.470
K2O              5.340      5.620      5.540      4.130      5.220      4.630
P2O5             0.008      0.034      0.014      0.083      0.059      0.044

             KHD-107-A  KHD-107-D  KHD-105-B-2
Sample Name
SiO2            75.450     75.430       76.120
TiO2             0.091      0.141        0.095
Al2O3           13.130     13.060       12.820
FeO*             0.800      0.790        0.850
MnO              0.016      0.014        0.010
MgO              0.090      0.220        0.120
CaO              0.960      1.170        0.940
Na2O             2.940      2.740        2.810
K2O              5.910      5.820        5.670
P2O5             0.028      0.035        0.013

## More tests below

In [4]:
import importlib
import sci_helpers
importlib.reload(sci_helpers)
# also reload the submodule directly if needed
import sci_helpers.stacked_to_samples as sts
importlib.reload(sts)
from sci_helpers.stacked_to_samples import stacked_file_to_wrangled, merge_wrangled_results

### Test of loading a sheet on Monte Carlo synthetic compositions

In [5]:
# import (either direct submodule import or package-level import now that we exported it)
from sci_helpers.stacked_to_samples import stacked_file_to_wrangled, merge_wrangled_results

path = r"C:\Users\marvi\PycharmProjects\sci-cluster\sci-cluster\sci-data\Aplites_XRF_data\MonteCarlo_synthetic_compositions.csv"

# Proper multi-line call (no inline comments inside the parentheses)
results = stacked_file_to_wrangled(
    path,
    anchor='SiO2',
    skip_first_cols=6,        # skip left A..F metadata -> start at G
    synthetic_rows=200,       # take 200 rows after each synthetic header
    auto_detect_skip=False,
    blank_row_tolerance=50
)

# iterate all detected stacked datasets and show them
import os
from IPython.display import display

print("datasets found:", len(results))

dataset_frames = {}  # name -> df (with sample names as index)
for i, ds in enumerate(results, start=1):
    # name from Tab Names column (or fallback)
    raw_name = ds.get('dataset_name')
    name = raw_name if raw_name and raw_name.strip() else f'dataset_{i}'
    samples = ds.get('samples_list', [])
    oxides = ds.get('oxides_order', [])
    notes = ds.get('notes', [])

    print(f"--- Dataset {i} : {name} ---")
    print(" anchor (row,col):", ds.get('anchor'))
    print(" col_offset:", ds.get('col_offset'))
    print(" #samples:", len(samples))
    print(" oxides_order:", oxides)
    print(" notes (first 5):", notes[:5])
    if samples:
        print(" first sample row (0):", samples[0])
    else:
        print(" (no samples found)")

    # Build a tidy DataFrame view for this dataset and display it
    df_block = ds.get('df')
    try:
        # set index from samples_list sample names (preserve order)
        sample_index = [str(s[0]) for s in samples]
        df_view = df_block.copy()
        df_view.index = sample_index
    except Exception:
        df_view = df_block.copy()
    display(df_view.head())

    # store for later merging/export
    dataset_frames[name] = df_view

datasets found: 17
--- Dataset 1 : KCP-109-C ---
 anchor (row,col): (1, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 1, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KCP-109-C_compositions.csv']
 first sample row (0): ['KCP-109-B', 76.28822443, 0.059669847, 13.04695036, 0.643322296, 0.035780297, 0.101281661, 0.642557927, 4.489726469, 3.954553845, 0.021808209]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
KCP-109-B,76.288224,0.059670,13.046950,0.643322,0.035780,0.101282,0.642558,4.489726,3.954554,0.021808
KCP-109-A,76.129650,0.075127,12.908501,0.667325,0.026542,0.127045,0.710470,4.316284,4.063871,-0.002402
KCP-110-A,74.962688,0.061927,12.960715,0.656584,0.027906,0.080919,0.659863,4.401716,3.982320,0.008698
KHD-106-A,75.501964,0.065099,12.845957,0.655491,0.032188,0.097903,0.708541,4.193391,3.938005,0.013951
KHD-105-G,75.391956,0.087528,13.068616,0.697873,0.033906,0.135814,0.742119,4.360707,4.133836,0.010315

--- Dataset 2 : KCP-109-B ---
 anchor (row,col): (208, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 208, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KCP-109-B_compositions.csv']
 first sample row (0): ['nan', 76.5013638, 0.065759029, 12.45939442, 0.518972786, 0.024787721, 0.072155292, 0.570261896, 3.903717416, 4.530558631, 0.005839597]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,76.501364,0.065759,12.459394,0.518973,0.024788,0.072155,0.570262,3.903717,4.530559,0.005840
nan,76.753695,0.077744,12.425437,0.528506,0.026818,0.033276,0.563422,3.672927,4.584184,0.007011
nan,76.335021,0.059368,12.553869,0.479527,0.021943,0.026918,0.522082,4.158732,4.671548,0.007514
nan,76.686630,0.057436,12.726127,0.550799,0.022482,0.025945,0.520658,4.151702,4.540391,-0.002878
nan,77.262050,0.065859,12.623770,0.490982,0.023843,0.056295,0.529913,4.059493,4.530927,0.001171

--- Dataset 3 : KCP-109-A ---
 anchor (row,col): (415, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 415, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KCP-109-A_compositions.csv']
 first sample row (0): ['nan', 76.67049527, 0.07269311, 12.56150844, 0.61610213, 0.028580365, 0.0538821, 0.489936128, 3.920815604, 4.50988437, -0.000890598]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,76.670495,0.072693,12.561508,0.616102,0.028580,0.053882,0.489936,3.920816,4.509884,-0.000891
nan,75.732423,0.097454,12.553464,0.620314,0.032296,0.047693,0.593992,3.904562,4.542730,0.002132
nan,76.836800,0.070822,12.405920,0.618212,0.028772,0.027358,0.533010,3.937971,4.521860,0.000656
nan,76.033673,0.077370,12.478581,0.629338,0.030529,0.085332,0.545223,4.114216,4.380109,0.004099
nan,77.072484,0.093774,12.798868,0.608924,0.026185,0.042271,0.505456,3.916975,4.505365,0.002687

--- Dataset 4 : KCP-110-A ---
 anchor (row,col): (622, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 622, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KCP-110-A_compositions.csv']
 first sample row (0): ['nan', 71.5695183, 0.429554, 13.7598338, 2.412299192, 0.058812258, 0.685839276, 2.531023689, 4.207918986, 2.563682796, 0.147457366]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,71.569518,0.429554,13.759834,2.412299,0.058812,0.685839,2.531024,4.207919,2.563683,0.147457
nan,71.887800,0.425165,13.873942,2.473399,0.050778,0.644770,2.483475,4.313234,2.490384,0.148123
nan,72.256992,0.398373,13.665142,2.074795,0.063201,0.658371,2.523159,4.028185,2.519490,0.143812
nan,72.129147,0.430263,13.729751,2.246201,0.061106,0.677788,2.505770,4.048764,2.561696,0.137312
nan,72.300103,0.409799,13.511862,2.215728,0.055882,0.642230,2.466341,4.088602,2.517321,0.132275

--- Dataset 5 : KHD-106-A ---
 anchor (row,col): (829, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 829, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KHD-106-A_compositions.csv']
 first sample row (0): ['nan', 75.76030046, 0.10788774, 12.63004032, 1.071039623, 0.032753133, 0.129983995, 1.089804745, 3.292870972, 4.990043211, 0.055752101]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,75.760300,0.107888,12.630040,1.071040,0.032753,0.129984,1.089805,3.292871,4.990043,0.055752
nan,75.351755,0.125147,12.871368,1.176387,0.038239,0.186905,1.106472,3.141040,4.957328,0.066201
nan,75.696147,0.131008,12.834257,1.144412,0.038875,0.155013,1.030634,3.001964,4.958498,0.060128
nan,75.301611,0.129642,12.835617,1.109034,0.038888,0.136435,1.044252,3.438435,4.877991,0.043304
nan,76.091915,0.152506,12.751830,1.196967,0.032409,0.207202,1.070233,3.332463,4.904000,0.049761

--- Dataset 6 : KHD-105-G ---
 anchor (row,col): (1036, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 1036, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KHD-105-G_compositions.csv']
 first sample row (0): ['nan', 76.13232376, 0.06592037, 13.23835425, 0.477676732, 0.00152333, 0.030883465, 0.94760921, 3.113566132, 5.400500418, 0.014109948]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,76.132324,0.065920,13.238354,0.477677,0.001523,0.030883,0.947609,3.113566,5.400500,0.014110
nan,76.061361,0.058278,12.841112,0.461339,0.004604,0.041522,0.932331,3.127664,5.391347,0.005391
nan,76.560103,0.056875,12.791583,0.463560,0.006079,0.058936,0.955497,3.058044,5.339196,0.005147
nan,75.481848,0.035121,12.827762,0.369008,0.004429,0.051222,0.913692,3.187561,5.426678,0.009788
nan,76.121925,0.059618,13.069942,0.490973,0.005208,0.053701,0.990377,3.106327,5.309857,0.005797

--- Dataset 7 : KHD-105-D ---
 anchor (row,col): (1243, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 1243, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KHD-105-D_compositions.csv']
 first sample row (0): ['nan', 76.20992234, 0.082669813, 13.11733544, 0.658422611, 0.01000118, 0.088065529, 1.017840081, 3.464982887, 4.785536418, 0.003729439]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,76.209922,0.082670,13.117335,0.658423,0.010001,0.088066,1.017840,3.464983,4.785536,0.003729
nan,76.675805,0.092849,13.008610,0.618348,0.009346,0.071942,1.031624,3.424272,4.771443,0.009845
nan,75.852548,0.087601,13.096590,0.659167,0.009657,0.101353,1.061094,3.390773,4.953818,0.004635
nan,76.221170,0.098807,13.157049,0.573577,0.008389,0.083750,1.013846,3.414706,4.827766,0.011675
nan,76.290695,0.084833,13.086782,0.693228,0.008574,0.102070,1.115387,3.607057,4.828967,0.010185

--- Dataset 8 : KHD-105-E ---
 anchor (row,col): (1450, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 1450, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KHD-105-E_compositions.csv']
 first sample row (0): ['nan', 75.83478839, 0.089305501, 12.74396896, 0.652508958, 0.008725911, 0.043161445, 0.890595503, 3.250168833, 5.460589572, 0.004333976]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,75.834788,0.089306,12.743969,0.652509,0.008726,0.043161,0.890596,3.250169,5.460590,0.004334
nan,76.640577,0.087738,12.793084,0.636894,0.005825,0.055257,0.934010,3.226595,5.377921,0.004341
nan,76.472262,0.082631,12.876133,0.602352,0.006539,0.044954,0.901634,3.262528,5.277811,0.004692
nan,76.428923,0.097037,13.280597,0.656370,0.008433,0.064189,0.860404,3.201787,5.309491,0.002170
nan,76.367603,0.109055,12.764747,0.661699,0.009870,0.097831,0.960687,3.372650,5.226062,0.003015

--- Dataset 9 : KKC-103-A ---
 anchor (row,col): (1657, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 1657, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KKC-103-A_compositions.csv']
 first sample row (0): ['nan', 76.21572698, 0.060195299, 12.7478098, 0.490256412, 0.007189473, 0.037914966, 0.9897645, 2.831297637, 5.586667862, 0.032475279]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,76.215727,0.060195,12.747810,0.490256,0.007189,0.037915,0.989765,2.831298,5.586668,0.032475
nan,76.105987,0.077952,12.692332,0.485245,0.003995,0.052712,1.023753,2.903798,5.664668,0.036103
nan,76.644318,0.070622,12.890402,0.483756,0.005108,0.045653,0.996903,2.856502,5.665597,0.021284
nan,76.579497,0.084926,13.214339,0.556032,0.006213,0.060094,1.072180,2.751522,5.493939,0.031720
nan,76.567130,0.075058,12.818053,0.505144,0.004042,0.063309,0.969664,2.858089,5.685052,0.045204

--- Dataset 10 : KHD-105-B ---
 anchor (row,col): (1869, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 1869, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KHD-105-B_compositions.csv']
 first sample row (0): ['nan', 76.24788691, 0.085982998, 12.59923364, 0.529824763, 0.005963566, 0.031209292, 0.94263597, 2.937677487, 5.580744209, 0.014770458]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,76.247887,0.085983,12.599234,0.529825,0.005964,0.031209,0.942636,2.937677,5.580744,0.014770
nan,77.259792,0.061147,13.009588,0.566671,0.005385,0.055814,1.028077,2.969172,5.636153,0.000421
nan,75.447020,0.069294,12.956642,0.603776,0.005872,0.054491,0.971510,3.036581,5.649474,0.006684
nan,76.434825,0.087209,13.181129,0.594231,0.006178,0.075908,1.003735,2.912401,5.499282,0.018679
nan,75.874208,0.071957,12.667837,0.620608,0.008938,0.076835,1.005001,3.022162,5.510418,0.024420

--- Dataset 11 : KCP-114-A ---
 anchor (row,col): (2076, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 2076, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KCP-114-A_compositions.csv']
 first sample row (0): ['nan', 75.65994268, 0.129475719, 12.8261332, 0.781774979, 0.023503928, 0.220140406, 1.084801442, 3.532383205, 4.641139669, 0.042499998]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,75.659943,0.129476,12.826133,0.781775,0.023504,0.220140,1.084801,3.532383,4.641140,0.042500
nan,75.803727,0.151979,13.001167,0.820742,0.023908,0.208886,1.090641,3.368615,4.604925,0.036649
nan,75.633786,0.146342,12.995944,0.827975,0.020157,0.205479,1.166427,3.403287,4.547261,0.035799
nan,75.863170,0.136236,12.880169,0.917635,0.020380,0.201609,1.121119,3.422971,4.540424,0.034159
nan,75.860354,0.118221,12.904635,0.847308,0.020726,0.222649,1.177313,3.469208,4.652554,0.036244

--- Dataset 12 : KHD-105-F ---
 anchor (row,col): (2283, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 2283, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KHD-105-F_compositions.csv']
 first sample row (0): ['nan', 71.83636745, 0.238540397, 14.30795385, 2.04261611, 0.045260991, 0.388541425, 2.143925414, 3.640077961, 4.189330496, 0.08512283]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,71.836367,0.238540,14.307954,2.042616,0.045261,0.388541,2.143925,3.640078,4.189330,0.085123
nan,71.875430,0.238639,14.574873,2.006714,0.039754,0.365255,2.167237,3.900759,3.956761,0.086305
nan,71.504751,0.235894,14.557300,1.974284,0.045296,0.348244,2.278774,3.845186,4.057123,0.092331
nan,72.015682,0.232447,14.593182,2.042915,0.044167,0.326773,2.162699,3.748687,4.106815,0.087610
nan,71.282563,0.283719,14.506426,1.891298,0.037547,0.321548,2.175100,3.733642,4.157639,0.078764

--- Dataset 13 : KHD-107-C ---
 anchor (row,col): (2490, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 2490, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KHD-107-C_compositions.csv']
 first sample row (0): ['nan', 74.17196557, 0.165667732, 13.19095442, 1.302905806, 0.012375385, 0.247371829, 1.47000021, 3.048612255, 5.294242118, 0.051083315]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,74.171966,0.165668,13.190954,1.302906,0.012375,0.247372,1.470000,3.048612,5.294242,0.051083
nan,74.413175,0.167209,13.537734,1.340790,0.022300,0.303816,1.384874,3.171102,5.272528,0.045562
nan,73.885780,0.178289,13.454592,1.319589,0.020278,0.284080,1.486197,3.119987,5.276217,0.046203
nan,74.316489,0.166933,13.444484,1.403684,0.017429,0.254225,1.507530,3.216602,5.191338,0.049938
nan,74.401840,0.177154,13.522652,1.290733,0.022332,0.257151,1.455287,3.051633,5.122756,0.055681

--- Dataset 14 : KHD-107-D ---
 anchor (row,col): (2697, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 2697, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KHD-107-D_compositions.csv']
 first sample row (0): ['nan', 75.44022474, 0.169076793, 13.38010016, 0.968623196, 0.017612802, 0.29202622, 1.216203204, 2.886930185, 5.822792029, 0.047799856]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,75.440225,0.169077,13.380100,0.968623,0.017613,0.292026,1.216203,2.886930,5.822792,0.047800
nan,75.629139,0.204561,13.018211,0.848780,0.012729,0.300303,1.138662,2.556799,5.754331,0.008951
nan,74.967832,0.100512,13.297876,0.952408,0.021063,0.245107,1.169296,2.665660,5.870543,-0.033457
nan,75.402993,0.103448,13.110769,0.602596,0.010599,0.298154,1.084463,2.923483,5.867064,0.043877
nan,75.577012,0.142649,12.954693,0.447997,0.011112,0.394920,1.271401,2.721346,5.808749,0.016440

--- Dataset 15 : KHD-107-A ---
 anchor (row,col): (2904, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 2904, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KHD-107-A_compositions.csv']
 first sample row (0): ['nan', 75.88397842, -0.031760326, 12.92754179, 0.941444136, 0.027485408, -0.070996567, 1.032797631, 2.966608489, 5.882109232, 0.037594489]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,75.883978,-0.031760,12.927542,0.941444,0.027485,-0.070997,1.032798,2.966608,5.882109,0.037594
nan,75.550830,0.081111,13.134925,0.532107,0.016126,0.735117,0.929872,3.012012,5.978073,-0.051594
nan,75.294125,0.065658,13.344581,0.742842,0.011035,0.094410,0.535229,3.009136,5.874636,0.068524
nan,75.520040,0.161251,13.228167,0.796564,0.016486,-0.342415,0.914685,2.770607,5.925962,-0.046687
nan,74.859716,0.108441,13.297416,1.058667,0.030481,0.618568,0.756934,3.160182,5.930469,0.069242

--- Dataset 16 : KHD-105-B-2 ---
 anchor (row,col): (3111, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 3111, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_KHD-105-B-2_compositions.csv']
 first sample row (0): ['nan', 75.81826017, 0.094469475, 13.01280919, 0.754342726, 0.010480288, 0.107755815, 0.919397818, 2.81130534, 5.644436196, 0.014738099]

,SiO2,TiO2,Al2O3,FeO,MnO,MgO,CaO,Na2O,K2O,P2O5
nan,75.818260,0.094469,13.012809,0.754343,0.010480,0.107756,0.919398,2.811305,5.644436,0.014738
nan,76.677459,0.090026,13.025951,0.830653,0.014227,0.104769,0.974588,2.941506,5.686728,0.011531
nan,76.400974,0.084808,12.691868,0.850459,0.004085,0.142696,0.993341,3.023797,5.721332,0.011278
nan,76.127229,0.119005,13.019009,0.900363,0.008099,0.130000,0.949643,2.934279,5.671418,0.016348
nan,76.746774,0.088971,12.881043,0.915008,0.014195,0.089491,0.910613,2.761615,5.697037,0.015633

--- Dataset 17 : TEMPLATE1 ---
 anchor (row,col): (3318, 1)
 col_offset: 6
 #samples: 200
 oxides_order: ['SiO2', 'TiO2', 'Al2O3', 'FeO', 'MnO', 'MgO', 'CaO', 'Na2O', 'K2O', 'P2O5']
 notes (first 5): ['Detected synthetic header at row 3318, columns 1-10', 'WROTE_CSV: C:\\Users\\marvi\\PycharmProjects\\sci-cluster\\sci-cluster\\sci-data\\wrangled-outputs\\wrangled_TEMPLATE1_compositions.csv']
 first sample row (0): ['nan', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

     SiO2  TiO2  Al2O3  FeO  MnO  MgO  CaO  Na2O  K2O  P2O5
nan   NaN   NaN    NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN
nan   NaN   NaN    NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN
nan   NaN   NaN    NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN
nan   NaN   NaN    NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN
nan   NaN   NaN    NaN  NaN  NaN  NaN  NaN   NaN  NaN   NaN

In [6]:
import inspect
print(inspect.signature(stacked_file_to_wrangled))

(path: str, sheet_name: Optional[str] = None, anchor: str = 'SiO2', oxide_names: Optional[List[str]] = None, min_oxides: int = 3, blank_row_tolerance: int = 50, auto_name_prefix: str = 'sample_auto_', write_out: Optional[str] = None, skip_first_cols: int = 0, auto_detect_skip: bool = False, synthetic_rows: Optional[int] = None, header_scan_rows: Optional[int] = None, tab_name_col: int = 0) -> List[Dict]